#!/bin/sh
#
# @copyright@
# Copyright (c) 2006 - 2017 Teradata
# All rights reserved. Stacki(r) v5.x stacki.com
# https://github.com/Teradata/stacki/blob/master/LICENSE.txt
# @copyright@

unset PYTHONPATH
export LD_LIBRARY_PATH=/opt/stack/lib

/opt/stack/bin/fix_partition.py