#!/bin/sh
#
# @copyright@
# @copyright@

log "==============================="
log "Starting F10-a-stacki-debug ..."
log "==============================="

unset PYTHONPATH
export LD_LIBRARY_PATH=/opt/stack/lib

grep stack-debug /proc/cmdline 2>&1 > /dev/null
if [ $? -eq 0 ]
then
	touch /tmp/wait
	echo "Stacki debug wait loop - remove /tmp/wait to continue"
	while [ -f /tmp/wait ]
	do
		sleep 1
		/opt/stack/bin/stacki-status.py install wait 2
	done
fi

/opt/stack/bin/stacki-status.py install complete rebooting
