#!/bin/sh
#
# $Id$
#
# chkconfig: 3 99 99 
#
# description: boot pre script
#
# @rocks@
# Copyright (c) 2000 - 2010 The Regents of the University of California
# All rights reserved. Rocks(r) v5.4 www.rocksclusters.org
# https://github.com/Teradata/stacki/blob/master/LICENSE-ROCKS.txt
# @rocks@
#
# $Log$
# Revision 1.4  2010/09/07 23:53:03  bruno
# star power for gb
#
# Revision 1.3  2009/05/09 00:23:21  mjk
# mv the file and then source it
#
# Revision 1.2  2009/05/01 19:07:05  mjk
# chimi con queso
#
# Revision 1.1  2009/04/24 19:45:27  mjk
# added rocks-pre/post init scripts
#

. /etc/rc.d/init.d/functions

run_post() {
	if [ -f /etc/sysconfig/stack-post ]; then
		/bin/mv /etc/sysconfig/stack-post /root/stack-post.sh
		/bin/bash /root/stack-post.sh >> /root/stack-post.log 2>&1
	fi
}

case "$1" in
start)
	action "Running stacki Firstboot Post script" run_post
;;

stop)
	;;

*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

