#!/bin/sh
#
# $Id$
#
# chkconfig: 3 00 00 
#
# description: boot pre script
#
# @rocks@
# Copyright (c) 2000 - 2010 The Regents of the University of California
# All rights reserved. Rocks(r) v5.4 www.rocksclusters.org
# https://github.com/Teradata/stacki/blob/master/LICENSE-ROCKS.txt
# @rocks@
#
# $Log$
# Revision 1.3  2010/09/07 23:53:03  bruno
# star power for gb
#
# Revision 1.2  2009/05/01 19:07:05  mjk
# chimi con queso
#
# Revision 1.1  2009/04/24 19:45:27  mjk
# added stack-pre/post init scripts
#

. /etc/rc.d/init.d/functions

run_pre() {
	if [ -f /etc/sysconfig/stack-pre ]; then
		/bin/bash /etc/sysconfig/stack-pre >> /root/stack-pre.log 2>&1
		/bin/mv /etc/sysconfig/stack-pre /root/stack-pre.sh
	fi
}

case "$1" in
start)
	action "Running stacki Firstboot Pre script" run_pre
;;

stop)
	;;

*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

