#!/bin/sh
#
# chkconfig: 3 99 00
#
# description: stacki shutdown
#
# @copyright@
# Copyright (c) 2006 - 2019 Teradata
# All rights reserved. Stacki(r) v5.x stacki.com
# https://github.com/Teradata/stacki/blob/master/LICENSE.txt
# @copyright@

. /etc/rc.d/init.d/functions

case "$1" in
start)
	;;

stop)
	/opt/stack/bin/smq-publish -t120 shutdown
	;;

*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

