#!/bin/sh
#
# $Id$
#
# chkconfig: 3 99 99
#
# description: silence kernel warning on the console
#
# @rocks@
# Copyright (c) 2000 - 2010 The Regents of the University of California
# All rights reserved. Rocks(r) v5.4 www.rocksclusters.org
# https://github.com/Teradata/stacki/blob/master/LICENSE-ROCKS.txt
# @rocks@
#
# $Log$
# Revision 1.11  2010/09/07 23:53:03  bruno
# star power for gb
#
# Revision 1.10  2009/05/01 19:07:05  mjk
# chimi con queso
#
# Revision 1.9  2008/10/18 00:55:58  mjk
# copyright 5.1
#
# Revision 1.8  2008/03/06 23:41:41  mjk
# copyright storm on
#
# Revision 1.7  2007/06/23 04:03:21  mjk
# mars hill copyright
#
# Revision 1.6  2006/09/11 22:47:05  mjk
# monkey face copyright
#
# Revision 1.5  2006/08/10 00:09:29  mjk
# 4.2 copyright
#
# Revision 1.4  2005/10/12 18:08:35  mjk
# final copyright for 4.1
#
# Revision 1.3  2005/09/16 01:02:15  mjk
# updated copyright
#
# Revision 1.2  2005/05/24 21:21:50  mjk
# update copyright, release is not any closer
#
# Revision 1.1  2005/03/01 02:02:44  mjk
# moved from core to base
#
# Revision 1.3  2004/03/25 03:15:30  bruno
# touch 'em all!
#
# update version numbers to 3.2.0 and update copyrights
#
# Revision 1.2  2003/12/23 00:39:57  mjk
# gotta learn how to program
#
# Revision 1.1  2003/12/22 19:19:22  mjk
# added rocks-dmesg
#

. /etc/rc.d/init.d/functions


case "$1" in
start)
	action "Turn off kernel logging to console:" /bin/dmesg -n1
	;;

stop)
	;;

*)
	echo "Usage: $0 {start|stop}"
	RETVAL=1	
esac

exit $RETVAL

