---
- name: Add Centos pallet
  command: /opt/stack/bin/stack add pallet /export/isos/CentOS-7-x86_64-Everything-1810.iso
  when: ansible_distribution == "CentOS"

- name: Add SLES 12 pallet
  command: /opt/stack/bin/stack add pallet /export/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
  when: ansible_distribution == "SLES" and ansible_distribution_version == "12.3"

- name: Add SLES 15 pallet
  command: /opt/stack/bin/stack add pallet /export/isos/SLE-15-SP1-Installer-DVD-x86_64-GM-DVD1.iso
  when: ansible_distribution == "SLES" and ansible_distribution_version == "15.1"

- name: Enable {{ ansible_distribution }} pallet for default box
  command: /opt/stack/bin/stack enable pallet {{ ansible_distribution }}

- name: Enable {{ ansible_distribution }} pallet for frontend box
  command: /opt/stack/bin/stack enable pallet {{ ansible_distribution }} box=frontend

- name: Set up SLES 15 packages pallet
  block:
  - name: Add SLES 15 packages pallet
    command: /opt/stack/bin/stack add pallet /export/isos/SLE-15-SP1-Packages-x86_64-GM-DVD1.iso

  - name: Enable SLES 15 packages pallet for default box
    command: /opt/stack/bin/stack enable pallet Packages-1

  - name: Enable SLES 15 packages pallet for frontend box
    command: /opt/stack/bin/stack enable pallet Packages-1 box=frontend
  when: ansible_distribution == "SLES" and ansible_distribution_version == "15.1"
