---
- name: Set up zypper
  block:
    - name: Download SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
      get_url:
        url: http://stacki-builds.labs.teradata.com/installer-isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
        dest: /export/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
        checksum: "sha1:d5e880817ab39124d2be0a8f5e81498143067c10"
        mode: 0644

    - name: Add SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso to zypper
      zypper_repository:
        name: os
        repo: iso:/?iso=/export/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
        state: present
        runrefresh: true
  when: ansible_distribution == "SLES"
