#!/bin/sh
#
# $Id$
#
# chkconfig: 3 99 99
#
# description: set the correct number of CPUs for the frontend on each boot
#
# @Copyright@
# Copyright (c) 2000 - 2010 The Regents of the University of California
# All rights reserved. Rocks(r) v5.4 www.rocksclusters.org
# https://github.com/Teradata/stacki/blob/master/LICENSE-ROCKS.txt
# @Copyright@
#

. /etc/rc.d/init.d/functions


case "$1" in
start)
	cpus=`grep 'processor' /proc/cpuinfo | wc -l`
	action "Setting the number of CPUs in the database:" \
		/opt/stack/bin/stack set host attr localhost attr=cpus value=$cpus
	;;

stop)
	;;

*)
	echo "Usage: $0 {start|stop}"
	RETVAL=1	
esac

exit $RETVAL

