---
- hosts: frontend
  tasks:
    - name: Barnacle the frontend
      import_role:
        name: barnacle
    
    - name: Set up the OS pallet
      import_role:
        name: os-pallet

    - name: Set up the Vagrant cart
      import_role:
        name: vagrant-cart
