---
- hosts: frontend
  tasks:
    - name: Create /export/isos
      file:
        path: /export/isos
        state: directory

    - name: Barnacle the frontend
      import_role:
        name: barnacle

    - name: Set up system test-suite coverage
      import_role:
        name: system-coverage
      when: lookup('env','SYSTEM_COVERAGE') == '1'

    - name: Set up the OS pallet
      import_role:
        name: os-pallet

    - name: Set up the Vagrant cart
      import_role:
        name: vagrant-cart

    - name: See if /export/src exists
      stat:
        path: /export/src
      register: result

    - name: Set up the src files if they exist
      import_role:
        name: use-src
      when: result.stat.exists
